### ISSUE TITLE
call scidbpy.interface.reap() while connected to a 15.x trunk.  The app gets a traceback from connection failure of scidb-py.  /var/log/message about imuxsock dropping packets is immediately followed by shim segfault message.

### ISSUE THREAD

**Issue by jmcq** [Paradigm4/shim#33]
I will attempt to make a small repro case separate from the Neural Network application where this is currently happening.

Note that the shim failure is always preceded by a message about "imuxsock begins to drop messages due to rate-limiting"

$ sudo /etc/rc.d/init.d/shimsvc restart
[sudo] password for james: 
1. SCIDB_DIR is
2. SCIDB_DIR is /opt/scidb/15.6
1. SCIDB_DIR is
2. SCIDB_DIR is /opt/scidb/15.6
Stopping shim
Couldn't kill process 10265             (privilege error?)
1. SCIDB_DIR is
2. SCIDB_DIR is /opt/scidb/15.6
Starting shim
command is:
su root -c '/opt/scidb/15.6/bin/shim' -p 8080,8083s -n login -s 1239 -t /tmp/

$ python ./autoencoder_scidb.py 
[good output omitted, after traceback below there will be the shim output from /var/log/messages]
Traceback (most recent call last):
  File "./autoencoder_scidb.py", line 1097, in <module>
    executeSparseAutoencoder()
  File "./autoencoder_scidb.py", line 983, in executeSparseAutoencoder
    jac = True, options = {'maxiter': maxIter})
  File "/usr/lib64/python2.6/site-packages/scipy/optimize/_minimize.py", line 427, in minimize
    callback=callback, **options)
  File "/usr/lib64/python2.6/site-packages/scipy/optimize/lbfgsb.py", line 315, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/usr/lib64/python2.6/site-packages/scipy/optimize/lbfgsb.py", line 266, in func_and_grad
    f = fun(x, *args)
  File "/usr/lib64/python2.6/site-packages/scipy/optimize/optimize.py", line 282, in function_wrapper
    return function(*(wrapper_args + args))
  File "/usr/lib64/python2.6/site-packages/scipy/optimize/optimize.py", line 60, in __call__
    fg = self.fun(x, *args)
  File "./autoencoder_scidb.py", line 861, in sparseAutoencoderCost
    self.sdb.reap()
  File "/home/james/work/ex2v4python.jhm/scidbpy/interface.py", line 238, in reap   <-------------------
    self.query("remove({0})", array)
  File "/home/james/work/ex2v4python.jhm/scidbpy/interface.py", line 451, in query
    return self._execute_query(qstring)
  File "/home/james/work/ex2v4python.jhm/scidbpy/interface.py", line 1717, in _execute_query
    self._shim_execute_query(session_id, query, release=True)
  File "/home/james/work/ex2v4python.jhm/scidbpy/interface.py", line 1789, in _shim_execute_query
    result = self._shim_urlopen(url)
  File "/home/james/work/ex2v4python.jhm/scidbpy/interface.py", line 1747, in _shim_urlopen
    r = requests.get(url, verify=False, auth=self._auth)
  File "/usr/lib/python2.6/site-packages/requests-2.7.0-py2.6.egg/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests-2.7.0-py2.6.egg/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests-2.7.0-py2.6.egg/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.6/site-packages/requests-2.7.0-py2.6.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests-2.7.0-py2.6.egg/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('',))
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/james/work/ex2v4python.jhm/scidbpy/interface.py", line 238, in reap
    self.query("remove({0})", array)
  File "/home/james/work/ex2v4python.jhm/scidbpy/interface.py", line 451, in query
    return self._execute_query(qstring)
  File "/home/james/work/ex2v4python.jhm/scidbpy/interface.py", line 1704, in _execute_query
    session_id = self._shim_new_session()
  File "/home/james/work/ex2v4python.jhm/scidbpy/interface.py", line 1764, in _shim_new_session
    result = self._shim_urlopen(url)
  File "/home/james/work/ex2v4python.jhm/scidbpy/interface.py", line 1747, in _shim_urlopen
    r = requests.get(url, verify=False, auth=self._auth)
  File "/usr/lib/python2.6/site-packages/requests-2.7.0-py2.6.egg/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests-2.7.0-py2.6.egg/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests-2.7.0-py2.6.egg/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.6/site-packages/requests-2.7.0-py2.6.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests-2.7.0-py2.6.egg/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/james/work/ex2v4python.jhm/scidbpy/interface.py", line 238, in reap
    self.query("remove({0})", array)
  File "/home/james/work/ex2v4python.jhm/scidbpy/interface.py", line 451, in query
    return self._execute_query(qstring)
  File "/home/james/work/ex2v4python.jhm/scidbpy/interface.py", line 1704, in _execute_query
    session_id = self._shim_new_session()
  File "/home/james/work/ex2v4python.jhm/scidbpy/interface.py", line 1764, in _shim_new_session
    result = self._shim_urlopen(url)
  File "/home/james/work/ex2v4python.jhm/scidbpy/interface.py", line 1747, in _shim_urlopen
    r = requests.get(url, verify=False, auth=self._auth)
  File "/usr/lib/python2.6/site-packages/requests-2.7.0-py2.6.egg/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests-2.7.0-py2.6.egg/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests-2.7.0-py2.6.egg/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.6/site-packages/requests-2.7.0-py2.6.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.6/site-packages/requests-2.7.0-py2.6.egg/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))

[ excerpt of /var/log/syslog showing the shim segfault ]
Jun  9 15:42:44 salty2_xge shim: new_session 0
Jun  9 15:42:44 salty2_xge shim: new_session session id=203 ibuf=/tmp//shim_input_buf_rkWLy8 obuf=/tmp//shim_output_buf_BfeRcG opipe=/tmp//shim_output_pipe_TSWWQd
Jun  9 15:42:44 salty2_xge shim: /execute_query?release=1&query=remove%28py1101157027144_00005%29&id=203
Jun  9 15:42:44 salty2_xge shim: execute_query for session id 203
Jun  9 15:42:44 salty2_xge shim: execute_query 203 s->con = 0x7f7c04041e70 remove(py1101157027144_00005)
Jun  9 15:42:44 salty2_xge shim: execute_query 203 connected
Jun  9 15:42:44 salty2_xge shim: execute_query id=203 scidb queryid = 1101223967472
Jun  9 15:42:44 salty2_xge shim: execute_query 203 done, disconnecting
Jun  9 15:42:44 salty2_xge shim: execute_query releasing HTTP session 203
Jun  9 15:42:44 salty2_xge shim: cleanup_session releasing 203
Jun  9 15:42:44 salty2_xge shim: cleanup_session unlinking /tmp//shim_output_buf_BfeRcG
Jun  9 15:42:44 salty2_xge shim: cleanup_session unlinking /tmp//shim_output_pipe_TSWWQd
Jun  9 15:42:44 salty2_xge shim: /new_session?(null)
Jun  9 15:42:44 salty2_xge shim: creating generic pipe: /tmp//shim_generic_pipe204
Jun  9 15:42:44 salty2_xge shim: new_session 0
Jun  9 15:42:44 salty2_xge shim: new_session session id=204 ibuf=/tmp//shim_input_buf_Vd4NBL obuf=/tmp//shim_output_buf_H89Fmj opipe=/tmp//shim_output_pipe_LUEy7Q
Jun  9 15:42:44 salty2_xge shim: /execute_query?release=1&query=remove%28py1101157027144_00006%29&id=204
Jun  9 15:42:44 salty2_xge shim: execute_query for session id 204
Jun  9 15:42:44 salty2_xge shim: execute_query 204 s->con = 0x7f7bfc041e70 remove(py1101157027144_00006)
Jun  9 15:42:44 salty2_xge shim: execute_query 204 connected
Jun  9 15:42:44 salty2_xge shim: execute_query id=204 scidb queryid = 1101223987473
Jun  9 15:42:44 salty2_xge shim: execute_query 204 done, disconnecting
Jun  9 15:42:44 salty2_xge rsyslogd-2177: imuxsock begins to drop messages from pid 30496 due to rate-limiting
Jun  9 15:42:44 salty2_xge kernel: shim[30505]: segfault at fffffffffffffff8 ip 00000036e5c9d25b sp 00007f7cdd654830 error 4 in libstdc++.so.6.0.13[36e5c00000+e8000]

**Comment by jmcq** [comment]
p4 ticket referrring to this ticket is #4820

**Comment by jmcq** [comment]
Note in the following lines from above:
Jun 9 15:42:44 salty2_xge rsyslogd-2177: imuxsock begins to drop messages from pid **30496** due to rate-limiting
Jun 9 15:42:44 salty2_xge kernel: shim[**30505**]: segfault at fffffffffffffff8 ip 00000036e5c9d25b sp 00007f7cdd654830 error 4 in libstdc++.so.6.0.13[36e5c00000+e8000]
**30496** was the pid of shim
**30505** appears to be the tid of a thread in shim

**Comment by jmcq** [comment]
looks like shim dies when it tries to print an exception?

Core was generated by `/opt/scidb/15.6/bin shim -p 8080,8083s -n login -s 1239 -t /tmp/'.
Program terminated with signal 11, Segmentation fault.

(gdb) where
#0  _M_is_leaked (this=0x7f5128042cd0, __str=Traceback (most recent call last):
  File "/usr/lib64/../share/gdb/python/libstdcxx/v6/printers.py", line 558, in to_string
    return self.val['_M_dataplus']['_M_p'].lazy_string (length = len)
RuntimeError: Cannot access memory at address 0xffffffffffffffe8
)
    at /usr/src/debug/gcc-4.4.7-20120601/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.h:184
#1  _M_grab (this=0x7f5128042cd0, __str=Traceback (most recent call last):
  File "/usr/lib64/../share/gdb/python/libstdcxx/v6/printers.py", line 558, in to_string
    return self.val['_M_dataplus']['_M_p'].lazy_string (length = len)
RuntimeError: Cannot access memory at address 0xffffffffffffffe8
)
    at /usr/src/debug/gcc-4.4.7-20120601/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.h:221
#2  std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (this=0x7f5128042cd0,
    __str=Traceback (most recent call last):
  File "/usr/lib64/../share/gdb/python/libstdcxx/v6/printers.py", line 558, in to_string
    return self.val['_M_dataplus']['_M_p'].lazy_string (length = len)
RuntimeError: Cannot access memory at address 0xffffffffffffffe8
)
    at /usr/src/debug/gcc-4.4.7-20120601/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.tcc:174
#3  0x000000000041f20d in scidb::Exception::Exception (this=0x7f5128042cb0)
    at /opt/scidb/14.12/include/system/Exceptions.h:141
#4  0x00007f515dcbd87b in UserException (this=0x7f5128042870)
    at /home/james/work/xScidbT_salty1/include/system/Exceptions.h:210
#5  scidb::UserException::raise (this=0x7f5128042870)
    at /home/james/work/xScidbT_salty1/src/system/Exceptions.cpp:211
#6  0x00007f515de01c34 in scidb::makeExceptionFromErrorMessageAndThrow (msg=Unhandled dwarf expression opcode 0xf3
)
    at /home/james/work/xScidbT_salty1/src/network/MessageUtils.cpp:299
#7  0x00007f515dcb1e4d in scidb::SciDBRemote::prepareQuery (this=Unhandled dwarf expression opcode 0xf3
)
    at /home/james/work/xScidbT_salty1/src/capi/SciDBRemote.cpp:201
#8  0x000000000041dd94 in prepare_query (result=0x7f51517f4bb0, con=0x7f5128041e70,
    query=0x7f5128040e00 "remove(py1101358290403_00012)", afl=1, err=0x7f51517f4bc0 "") at client.cpp:126
#9  0x000000000040bf7d in execute_query (conn=0x7f51280008c0, ri=0x7f51280008c0) at shim.c:1209
#10 0x000000000040cb2c in begin_request_handler (conn=0x7f51280008c0) at shim.c:1446
#11 0x000000000041a5e3 in handle_request (conn=0x7f51280008c0) at mongoose.c:4789
#12 0x000000000041c760 in process_new_connection (conn=0x7f51280008c0) at mongoose.c:5425
#13 0x000000000041ccfd in worker_thread (thread_func_param=0x1b8c9a0) at mongoose.c:5525
#14 0x0000003259c079d1 in start_thread (arg=0x7f51517fb700) at pthread_create.c:301
#15 0x00000032598e88fd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:115

**Comment by jmcq** [comment]
There are sufficient changes in the headers used by shim that it must be recompiled for 15.x.   We need an interim package to be prepared which is compiled against a recent version of trunk.  Otherwise each person using shim for 15.x must compile it themselves, as there is a ticket that [is/has] removing shim from scidb 3rdparty.

Meantime, the workaround is to install shim by building from source.
